-- =====================================================
-- REEFEY DATABASE UPDATE - COMPLETE BALI MARINE LIFE DATA
-- =====================================================
-- All 73 species from CSV converted to SQL upsert commands
-- =====================================================

-- Update columns for longer text
ALTER TABLE marine ALTER COLUMN description TYPE TEXT;
ALTER TABLE marine ALTER COLUMN image_url TYPE TEXT;
ALTER TABLE marine ALTER COLUMN fun_fact TYPE TEXT;
ALTER TABLE marine ALTER COLUMN diet TYPE TEXT;
ALTER TABLE marine ALTER COLUMN life_span TYPE TEXT;
ALTER TABLE marine ALTER COLUMN reproduction TYPE TEXT;
ALTER TABLE marine ALTER COLUMN migration TYPE TEXT;

-- =====================================================
-- CREATE UPSERT FUNCTION
-- =====================================================
CREATE OR REPLACE FUNCTION upsert_marine_species(
    p_name VARCHAR(255),
    p_scientific_name VARCHAR(255),
    p_category VARCHAR(50),
    p_rarity INTEGER,
    p_size_min_cm DECIMAL(8, 2),
    p_size_max_cm DECIMAL(8, 2),
    p_habitat_type TEXT[],
    p_diet TEXT,
    p_behavior TEXT,
    p_danger VARCHAR(50),
    p_venomous BOOLEAN,
    p_description TEXT,
    p_life_span TEXT,
    p_reproduction TEXT,
    p_migration TEXT,
    p_endangered VARCHAR(100),
    p_fun_fact TEXT,
    p_image_url TEXT
) RETURNS INTEGER AS $$
DECLARE
    v_id INTEGER;
BEGIN
    UPDATE marine SET
        scientific_name = p_scientific_name,
        category = p_category,
        rarity = p_rarity,
        size_min_cm = p_size_min_cm,
        size_max_cm = p_size_max_cm,
        habitat_type = p_habitat_type,
        diet = p_diet,
        behavior = p_behavior,
        danger = p_danger,
        venomous = p_venomous,
        description = p_description,
        life_span = p_life_span,
        reproduction = p_reproduction,
        migration = p_migration,
        endangered = p_endangered,
        fun_fact = p_fun_fact,
        image_url = p_image_url,
        updated_at = NOW()
    WHERE name = p_name
    RETURNING id INTO v_id;
    
    IF v_id IS NULL THEN
        INSERT INTO marine (
            name, scientific_name, category, rarity, size_min_cm, size_max_cm,
            habitat_type, diet, behavior, danger, venomous, description,
            life_span, reproduction, migration, endangered, fun_fact, image_url
        ) VALUES (
            p_name, p_scientific_name, p_category, p_rarity, p_size_min_cm, p_size_max_cm,
            p_habitat_type, p_diet, p_behavior, p_danger, p_venomous, p_description,
            p_life_span, p_reproduction, p_migration, p_endangered, p_fun_fact, p_image_url
        ) RETURNING id INTO v_id;
    END IF;
    
    RETURN v_id;
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- INSERT ALL 73 SPECIES
-- =====================================================

SELECT upsert_marine_species('Reef manta ray', 'Mobula alfredi', 'Fishes', 3, 300.0, 500.0, ARRAY['Cleaning stations (e.g.', 'Nusa Penida)', 'coastal', 'oceanic'], 'Zooplankton (filter feeding)', 'Filter-feeder; visits cleaning stations; gentle in currents.', 'Low', true, 'Reef manta ray: occasional cleaning stations (e.g. near Nusa Penida (harmless) in Bali', '~40–50+ yrs', 'Aplacental live‑bearer; ~1 pup/12–13 mo', 'Regional movements with site fidelity', 'Vulnerable (global)', 'One of the largest brains among fishes', 'https://nusapenida.org/wp-content/uploads/2020/11/Ikan-pari-Manta-Nusa-Penida-Bali.jpg');
SELECT upsert_marine_species('Ocean sunfish (mola)', 'Mola alexandrini', 'Fishes', 2, 200.0, 300.0, ARRAY['Deep pelagic', 'visits Nusa Penida'], 'Jellies/gelatinous zooplankton', 'Pelagic drifter; seasonal; visits cleaning stations; shy.', 'Low', false, 'Ocean sunfish (mola): rare deep pelagic near Nusa Penida in Bali', 'Long (uncertain)', 'Pelagic broadcast spawner; very fecund', 'Vertical migrations; cleaning stations', 'Not clearly assessed; related spp. Vulnerable', 'Often miscalled M. mola; Bali is M. alexandrini', 'https://lh5.googleusercontent.com/VzJ_iNbp_DKD-h54eI5s_-HkaIiCP2aKpOIBh-avF3OqNPAMivHphQWx8smxWvNzo6oH1q_j3OMQQj0vyhUTbOzD_arP4Q99xGwd9FTIl-ykEL4JNa_ysz6HxqIVdhNRWC3YFx1o');
SELECT upsert_marine_species('Blacktip reef shark', 'Carcharhinus melanopterus', 'Fishes', 3, 120.0, 170.0, ARRAY['Shallow reefs', 'lagoons'], 'Fish, cephalopods, crustaceans', 'Reef patrols; wary of divers; active crepuscular hunter.', 'Medium', false, 'Blacktip reef shark: occasional shallow reefs near Nusa Penida (caution needed) in Bali', '10–15+ yrs', 'Viviparous (live‑bearing)', 'Home ranges on reefs', 'Vulnerable (parts of range)', 'Distinct black fin tips', 'https://upload.wikimedia.org/wikipedia/commons/7/76/Blacktip_reef_shark_%28Carcharhinus_melanopterus%29_Moorea_5.jpg');
SELECT upsert_marine_species('Whitetip reef shark', 'Triaenodon obesus', 'Fishes', 4, 130.0, 160.0, ARRAY['Reefs', 'caves by day'], 'Reef fishes, octopus', 'Nocturnal benthic rover; rests in caves by day.', 'Low', false, 'Whitetip reef shark: common reefs near Tulamben (harmless) in Bali', '~20+ yrs', 'Viviparous', 'Resident small ranges', 'Near Threatened/Vulnerable regionally', 'Can rest on bottom (buccal pumping)', 'https://www.lotusbungalows.com/wp-content/uploads/2018/05/whitetip-reef-shark-1200x800.jpg');
SELECT upsert_marine_species('Grey reef shark', 'Carcharhinus amblyrhynchos', 'Fishes', 3, 150.0, 200.0, ARRAY['Outer reef slopes', 'drop‑offs'], 'Fish, cephalopods', 'Pelagic reef predator; patrols drop-offs; wary.', 'Medium', false, 'Grey reef shark: occasional outer reef slopes near Nusa Penida in Bali', '~20–25 yrs', 'Viviparous', 'Local movements along reef edges', 'Vulnerable (global)', 'Threat posture when agitated', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Corl0207_%2828225976491%29.jpg/2560px-Corl0207_%2828225976491%29.jpg');
SELECT upsert_marine_species('Blue‑spotted ribbontail ray', 'Taeniura lymma', 'Fishes', 4, 30.0, 70.0, ARRAY['Shallow sandy lagoons', 'reefs'], 'Crustaceans, worms, small fish', 'Benthic; hides in sand; venomous tail spines.', 'Medium', true, 'Blue‑spotted ribbontail ray: common shallow sandy lagoons near Amed (caution needed) in Bali', '~10–15 yrs', 'Ovoviviparous', 'Small home ranges', 'Near Threatened (some lists)', 'Bright blue warning spots', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Raya_de_arrecife_%28Taeniura_lymma%29%2C_mar_Rojo%2C_Egipto%2C_2023-04-14%2C_DD_64.jpg/2560px-Raya_de_arrecife_%28Taeniura_lymma%29%2C_mar_Rojo%2C_Egipto%2C_2023-04-14%2C_DD_64.jpg');
SELECT upsert_marine_species('Spotted eagle ray', 'Aetobatus ocellatus', 'Fishes', 3, 100.0, 200.0, ARRAY['Coastal reefs', 'sandy flats'], 'Mollusks, crustaceans', 'Glides over sand flats; digs for mollusks; shy.', 'Medium', true, 'Spotted eagle ray: occasional coastal reefs near Nusa Penida (drifts) (caution needed) in Bali', '~25 yrs (est.)', 'Ovoviviparous (live‑bearing)', 'Local/regional movements', 'Vulnerable (parts of range)', 'Digs with snout for prey', 'https://upload.wikimedia.org/wikipedia/commons/a/ad/Eagle_Ray_Turks_and_Caicos_Dec_15_2006.JPG');
SELECT upsert_marine_species('Reef stonefish', 'Synanceia verrucosa', 'Fishes', 3, 30.0, 40.0, ARRAY['Reef flats', 'rubble', 'camouflage'], 'Small fish & shrimp', 'Sedentary ambush predator; superb camouflage; extremely venomous.', 'Extreme', true, 'Reef stonefish: occasional reef flats near Padang Bai in Bali', 'Poorly documented', 'External fertilization; eggs on substrate', 'Sedentary ambush', 'Least Concern', 'Strikes prey in ~0.015 s', 'https://images.redseacreatures.com/creatures/images/reef-stonefish/1704015137885-633131365.jpeg');
SELECT upsert_marine_species('Common lionfish', 'Pterois volitans', 'Fishes', 4, 25.0, 38.0, ARRAY['Reefs', 'ledges', 'rubble'], 'Small fish & inverts', 'Slow ambush predator; spreads fins; venomous spines.', 'High', true, 'Common lionfish: common reefs near Tulamben (caution needed) in Bali', '~10–15 yrs (reported)', 'Frequent spawner; buoyant eggs', 'Site‑attached', 'Not threatened', 'Native to Indonesia; invasive in Atlantic', 'https://www.australiangeographic.com.au/wp-content/uploads/2023/03/shutterstock_1656062215-edited.jpg');
SELECT upsert_marine_species('Giant trevally (GT)', 'Caranx ignobilis', 'Fishes', 3, 80.0, 150.0, ARRAY['Lagoons', 'seaward reefs', 'estuaries (juv)'], 'Fish, cephalopods, crustaceans', 'Fast pelagic hunter; patrols currents and drop-offs.', 'Medium', false, 'Giant trevally (GT): occasional lagoons near Nusa Penida (caution needed) in Bali', 'Decades', 'Spawns on seaward reefs/banks', 'Local reef moves; spawning aggregations', 'Least Concern (globally)', 'Apex reef predator; clever hunting', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Caranx_ignobilis.jpg/1920px-Caranx_ignobilis.jpg');
SELECT upsert_marine_species('Giant moray', 'Gymnothorax javanicus', 'Fishes', 4, 100.0, 250.0, ARRAY['Reefs', 'rubble', 'caves', 'crevices'], 'Fish, crustaceans', 'Nocturnal ambush predator; retreats in crevices; bites if provoked.', 'Medium', true, 'Giant moray: common reefs near Tulamben (caution needed) in Bali', 'Likely decades', 'Broadcast spawner; leptocephalus larva', 'Larval drift; site‑attached adults', 'Least Concern', 'Cooperative hunts with groupers', 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Moray_eel_komodo.jpg');
SELECT upsert_marine_species('Titan triggerfish', 'Balistoides viridescens', 'Fishes', 4, 45.0, 75.0, ARRAY['Reefs', 'sandy patches', 'nest cones'], 'Urchins, mollusks, crustaceans', 'Territorial nester; may charge; avoid during breeding.', 'High', false, 'Titan triggerfish: common reefs near Nusa Penida (caution needed) in Bali', '~10+ yrs (est.)', 'Guards eggs in sand cone', 'Site‑attached territories', 'Least Concern', 'Chases divers from nest cone', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Titan_Triggerfish_imported_from_iNaturalist_photo_324702096_on_3_November_2024_%28edit%29.jpg/1920px-Titan_Triggerfish_imported_from_iNaturalist_photo_324702096_on_3_November_2024_%28edit%29.jpg');
SELECT upsert_marine_species('Clownfish (common)', 'Amphiprion ocellaris', 'Fishes', 4, 7.0, 11.0, ARRAY['Host anemones on reefs'], 'Plankton, small inverts, algae', 'Anemone symbiont; territorial pair; tends eggs.', 'Low', false, 'Clownfish (common): common host anemones on reefs near Tulamben in Bali', '~6–10 yrs (wild est.)', 'Eggs near anemone; male guards', 'Site‑attached to host', 'Least Concern', 'Symbiosis with anemones; sex change', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Amphiprion_ocellaris_%28Clown_anemonefish%29_by_Nick_Hobgood.jpg/1920px-Amphiprion_ocellaris_%28Clown_anemonefish%29_by_Nick_Hobgood.jpg');
SELECT upsert_marine_species('Banded sea krait (yellow‑lipped)', 'Laticauda colubrina', 'Creatures', 3, 80.0, 140.0, ARRAY['Reefs', 'comes ashore to rest', 'lay'], 'Eels, small fish', 'Air-breathing; hunts eels; docile but highly venomous.', 'High', true, 'Banded sea krait (yellow‑lipped): occasional reefs near Nusa Penida (ledges) (harmless) in Bali', 'Several yrs', 'Egg‑laying on land', 'Local foraging circuits', 'Not globally endangered', 'Amphibious lifestyle (land & sea)', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Banded_Sea_Krait_%28Laticauda_colubrina%29_%2814641328165%29.jpg/2560px-Banded_Sea_Krait_%28Laticauda_colubrina%29_%2814641328165%29.jpg');
SELECT upsert_marine_species('Reef octopus', 'Octopus cyanea', 'Creatures', 4, 20.0, 100.0, ARRAY['Shallow reefs', 'rubble flats'], 'Crabs, mollusks, small fish', 'Nocturnal, curious; changes color; forages on reef.', 'Medium', true, 'Reef octopus: common shallow reefs near Amed (caution needed) in Bali', '~1–2 yrs', 'Semelparous; female guards eggs then dies', 'Small home ranges', 'Not threatened', 'Masters of color/texture change', 'https://reefguide.org/pix/dayoctopus8.jpg');
SELECT upsert_marine_species('Mimic octopus', 'Thaumoctopus mimicus', 'Creatures', 3, 15.0, 60.0, ARRAY['Muck', 'sandy bottoms'], 'Crustaceans, small fish', 'Sediment flats; imitates other animals; diurnal.', 'Medium', true, 'Mimic octopus: occasional muck near Amed (caution needed) in Bali', '~1–2 yrs', 'Semelparous; egg‑brooding', 'Sedentary small ranges', 'Data Deficient', 'Imitates lionfish, flatfish, sea snake', 'https://octonation.com/wp-content/uploads/2020/10/mimicoctopus6_web-scaled.jpg');
SELECT upsert_marine_species('Coconut octopus', 'Amphioctopus marginatus', 'Creatures', 3, 12.0, 40.0, ARRAY['Muck', 'sand', 'uses shells', 'coconuts'], 'Crabs, clams', 'Collects shells; bipedal walking; intelligent, shy.', 'Medium', true, 'Coconut octopus: occasional muck near Amed (caution needed) in Bali', '~1–2 yrs', 'Egg‑brooding; female guards', 'Local movements', 'Not widely assessed', 'Carries shells as mobile armor', 'https://octonation.com/wp-content/uploads/2020/10/coconutoctopus13_web-1536x1024.jpg');
SELECT upsert_marine_species('Broadclub cuttlefish', 'Sepia latimanus', 'Creatures', 4, 30.0, 50.0, ARRAY['Reefs', 'seagrass edges'], 'Crustaceans, fish', 'Color-wave displays; ambushes fish; often diurnal.', 'Low', false, 'Broadclub cuttlefish: common reefs near Padang Bai in Bali', '~1–2 yrs', 'Grape‑like egg clusters on corals/seagrass', 'Local seasonal moves', 'Not threatened', 'Dynamic color waves for communication', 'https://www.marinebio.org/wp-content/uploads/2017/05/broadclub-cuttlefish.png');
SELECT upsert_marine_species('Flamboyant cuttlefish', 'Metasepia pfefferi', 'Creatures', 3, 6.0, 8.0, ARRAY['Muck flats', 'sandy bottoms'], 'Small crustaceans & fish', 'Toxic flesh; walks on arms; flashing colors.', 'Low', false, 'Flamboyant cuttlefish: occasional muck flats near Puri Jati (Lovina) in Bali', '~1–2 yrs', 'Eggs under ledges/debris', 'Sedentary', 'Data Deficient', 'Walks on arms with vivid displays', 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Flamboyant_Cuttlefish.jpg');
SELECT upsert_marine_species('Bigfin reef squid', 'Sepioteuthis lessoniana', 'Creatures', 4, 30.0, 60.0, ARRAY['Seagrass', 'nearshore waters'], 'Small fish, crustaceans', 'Schooling; rapid color change; pelagic at night.', 'Low', false, 'Bigfin reef squid: common seagrass near Sanur in Bali', '~1 yr', 'Egg capsules on seagrass/ropes', 'Short coastal moves', 'Not threatened', 'Rapid color changes in schools', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Bigfin_reef_squid_%2811760%29.jpg/1920px-Bigfin_reef_squid_%2811760%29.jpg');
SELECT upsert_marine_species('Peacock mantis shrimp', 'Odontodactylus scyllarus', 'Creatures', 3, 10.0, 18.0, ARRAY['Reef rubble', 'burrows'], 'Crabs, snails', 'Burrower; powerful smash strikes; bright coloration.', 'High', false, 'Peacock mantis shrimp: occasional reef rubble near Tulamben in Bali', 'Several yrs', 'Complex mating; egg brooding', 'Burrow‑based territories', 'Not listed as threatened', 'Sees polarized light; devastating strike', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Odontodactylus_scyllarus_Réunion.jpg/2560px-Odontodactylus_scyllarus_Réunion.jpg');
SELECT upsert_marine_species('Crown‑of‑thorns starfish', 'Acanthaster planci', 'Creatures', 3, 25.0, 35.0, ARRAY['Coral reefs', 'outbreak species'], 'Live coral polyps', 'Coral predator; outbreaks harm reefs; venomous spines.', 'High', true, 'Crown‑of‑thorns starfish: occasional coral reefs near Amed (caution needed) in Bali', '~3–4+ yrs', 'Broadcast spawner; high fecundity', 'Crawls; larvae drift', 'Not endangered (problem when overabundant)', 'Consumes coral tissue rapidly', 'https://upload.wikimedia.org/wikipedia/commons/8/8f/CrownofThornsStarfish_Fiji_2005-10-12.jpg');
SELECT upsert_marine_species('Blue sea star', 'Linckia laevigata', 'Creatures', 4, 20.0, 40.0, ARRAY['Shallow reefs', 'seagrass'], 'Biofilm, detritus', 'Slow grazer/scavenger; regenerates arms; gentle.', 'Low', false, 'Blue sea star: common shallow reefs near Padang Bai in Bali', 'Several yrs', 'Spawning; can clone from fragments', 'Minimal; slow', 'Least Concern', 'Regrows arms; vivid blue', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Linckia_laevigata_Tonga.jpg/1920px-Linckia_laevigata_Tonga.jpg');
SELECT upsert_marine_species('Green turtle', 'Chelonia mydas', 'Creatures', 4, 80.0, 120.0, ARRAY['Reefs', 'seagrass', 'coastal waters'], 'Seagrass, algae', 'Calm grazer; surfaces to breathe; site-faithful.', 'Low', false, 'Green turtle: common reefs near Nusa Penida in Bali', 'Decades', 'Beach nesting; clutches of eggs', 'Long migrations', 'Endangered', 'Adults mainly herbivorous', 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Hawaii_turtle_2.JPG');
SELECT upsert_marine_species('Spinner dolphin', 'Stenella longirostris', 'Creatures', 4, 130.0, 230.0, ARRAY['Offshore', 'coastal', 'often bow‑riding'], 'Small fish, squid', 'Offshore pods; acrobatic spins; approaches boats.', 'Low', false, 'Spinner dolphin: common offshore near Lovina offshore (dawn) in Bali', '20–30+ yrs', 'Live‑bearing; ~12‑mo gestation', 'Local/regional following prey', 'Varies by stock', 'Acrobatic spinning leaps', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/A_spinner_dolphin_in_the_Red_Sea.jpg/1920px-A_spinner_dolphin_in_the_Red_Sea.jpg');
SELECT upsert_marine_species('Staghorn coral (branching)', 'Acropora palifera (rep. Bali spp.)', 'Corals', 4, 20.0, 200.0, ARRAY['Shallow flats', 'slopes', 'North Bali', 'Menjangan'], 'Symbionts + plankton capture', 'Sessile branching coral; fast-growing; wave-exposed zones.', 'Medium', true, 'Staghorn coral (branching): common shallow flats near Menjangan (caution needed) in Bali', 'Decades (colonies)', 'Broadcast spawner; fragments easily', 'Sessile; larvae drift', 'Varies by species', 'Fast‑growing habitat former', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Hertshoon.jpg/2560px-Hertshoon.jpg');
SELECT upsert_marine_species('Bird’s nest coral', 'Seriatopora hystrix', 'Corals', 4, 20.0, 50.0, ARRAY['Current‑swept slopes', 'Menjangan', 'Penida'], 'Symbionts + zooplankton', 'Delicate branching; high-flow habitats; polyps extend at night.', 'Low', true, 'Bird’s nest coral: common current‑swept slopes near Menjangan (caution needed) in Bali', 'Years–decades', 'Brooding/spawning; fragments easily', 'Sessile; planula drift', 'Least Concern', 'Delicate branches shelter small fish', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Seriatopora_hystrix.jpg/500px-Seriatopora_hystrix.jpg');
SELECT upsert_marine_species('Long‑tentacle plate coral', 'Heliofungia actiniformis', 'Corals', 4, 20.0, 40.0, ARRAY['Sandy patches', 'Nusa Penida', 'slopes'], 'Zooplankton + symbionts', 'Solitary plate coral; long waving tentacles; daytime extension.', 'Low', true, 'Long‑tentacle plate coral: common sandy patches near Menjangan (caution needed) in Bali', 'Years', 'Sexual spawning; asexual budding', 'Sessile/free‑living on sand', 'Near Threatened in some lists', 'Free‑living single polyp resembling anemone', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Anemone_Coral_%28Heliofungia_actiniformis%29_%288491771017%29.jpg/500px-Anemone_Coral_%28Heliofungia_actiniformis%29_%288491771017%29.jpg');
SELECT upsert_marine_species('Sun coral (azooxanthellate)', 'Tubastraea coccinea', 'Corals', 4, 5.0, 20.0, ARRAY['Wrecks', 'overhangs (Tulamben Liberty)'], 'Zooplankton', 'Azooxanthellate; polyps open at night; non-photosynthetic.', 'Low', true, 'Sun coral (azooxanthellate): common wrecks near Tulamben (caution needed) in Bali', 'Years', 'Brooding & budding; spreads on structures', 'Sessile; larvae drift', 'Not globally threatened', 'Lacks symbionts; must capture food', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Coral_sol_%28Tubastraea_coccinea%29%2C_Cabo_Pulmo%2C_Baja_California%2C_México%2C_2024-12-19%2C_DD_22.jpg/1920px-Coral_sol_%28Tubastraea_coccinea%29%2C_Cabo_Pulmo%2C_Baja_California%2C_México%2C_2024-12-19%2C_DD_22.jpg');
SELECT upsert_marine_species('Sea fan (gorgonian)', 'Annella / Melithaea spp.', 'Corals', 4, 50.0, 200.0, ARRAY['Walls', 'drop‑offs', 'Menjangan dense'], 'Plankton (azooxanthellate)', 'Fan-shaped gorgonian; filter-feeding in currents; sessile.', 'Low', true, 'Sea fan (gorgonian): common walls near Menjangan (walls) (caution needed) in Bali', 'Years–decades', 'Broadcast spawner; branch growth', 'Sessile; larvae drift', 'Not broadly assessed', 'Home to pygmy seahorses in NW Bali', 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Melithaea_ochracea3.jpg');
SELECT upsert_marine_species('Indo-Pacific bottlenose dolphin', 'Tursiops aduncus', 'Creatures', 3, 200.0, 270.0, ARRAY['Coastal reefs', 'Channels', 'Bali–Lombok Strait'], 'Fish, squid, crustaceans', 'Highly social pods; bow-riding and foraging around current lines.', 'Low', false, 'Smaller bottlenose with speckled belly in adults; frequent coastal visitor.', '30–50 years', 'Single calf ~12-month gestation; calving every 3–6 years; extended maternal care.', 'Resident and short-range movements along straits and coasts.', 'IUCN: Near Threatened', 'Uses signature whistles—names—to keep track of pod mates.', 'https://upload.wikimedia.org/wikipedia/commons/8/87/Tursiops_aduncus%2C_Port_River%2C_Adelaide%2C_Australia_-_2003.jpg');
SELECT upsert_marine_species('Pantropical spotted dolphin', 'Stenella attenuata', 'Creatures', 2, 160.0, 260.0, ARRAY['Offshore pelagic', 'Bali–Lombok Strait'], 'Small fish and squid', 'Fast, acrobatic schools; often mixed-species groups offshore.', 'Low', false, 'Slender beak; adults develop heavy spotting—especially offshore form.', '~40 years', 'Single calf after ~11–12 months; long juvenile period.', 'Offshore movements tracking prey and currents; passes through strait.', 'IUCN: Least Concern', 'Spotting increases with age—calves are almost spotless.', 'https://www.fisheries.noaa.gov/s3//dam-migration/5184x3456-pantropical-spotted-dolphin-guam.jpg?itok=NhGwzx3d');
SELECT upsert_marine_species('Risso’s dolphin', 'Grampus griseus', 'Creatures', 2, 300.0, 380.0, ARRAY['Deep slope waters', 'Straits'], 'Mainly squid', 'Deep diver; adults covered in white scars from social interactions and prey.', 'Low', false, 'Blunt head, tall dorsal fin, grey body that whitens with age.', '~30–35+ years', 'Single calf after ~13–14 months.', 'Regional movements along deep-water corridors.', 'IUCN: Least Concern', 'Teeth mostly in the lower jaw—unusual among dolphins.', 'https://www.dolphinsafari.com/wp-content/uploads/sites/5012/2019/12/Rissos-Dolphin-Jumping-9976_copyright-Dolphin-Safari.jpg?auto=compress%2Cformat&w=1024&h=1024&fit=max');
SELECT upsert_marine_species('Short-finned pilot whale', 'Globicephala macrorhynchus', 'Creatures', 2, 350.0, 610.0, ARRAY['Offshore', 'Bali–Lombok Strait'], 'Squid, mesopelagic fishes', 'Matriarchal pods; tight social bonds and mass strandings recorded worldwide.', 'Low', false, 'Bulbous head, dark body; powerful, coordinated hunters.', '45+ years', 'Single calf after ~15 months; long calf dependency.', 'Broad roaming with prey layers; passes Indonesian straits episodically.', 'IUCN: Least Concern', 'Nicknamed “cheetahs of the deep” for sprint chases on dives.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Globicephala_macrorhynchus_Kurzflossen-Grindwal_DSCF8148.JPG/2560px-Globicephala_macrorhynchus_Kurzflossen-Grindwal_DSCF8148.JPG');
SELECT upsert_marine_species('Sperm whale', 'Physeter macrocephalus', 'Creatures', 1, 1100.0, 1600.0, ARRAY['Deep oceanic waters', 'Straits drop-offs'], 'Large squids and fish at great depths', 'Extreme deep diver using powerful echolocation clicks.', 'Low', false, 'Largest toothed whale with massive square head.', '60–70 years', 'Single calf after ~14–16 months; slow population growth.', 'Long-distance seasonal movements; rare in the strait.', 'IUCN: Vulnerable', 'Produces the ocean’s loudest biological sound.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Mother_and_baby_sperm_whale.jpg/2560px-Mother_and_baby_sperm_whale.jpg');
SELECT upsert_marine_species('Bryde’s whale', 'Balaenoptera edeni/brydei', 'Creatures', 2, 1200.0, 1550.0, ARRAY['Warm offshore waters', 'Straits'], 'Small schooling fish and krill', 'Baleen lunge-feeder; three ridges on the head are a field mark.', 'Low', false, 'Sleek rorqual occasionally transiting Indonesian passages.', '50+ years (est.)', 'Single calf after ~12 months.', 'Regional movements; less migratory than many baleen whales.', 'IUCN: Least Concern', 'Often feeds just below bait balls, pushing prey to the surface.', 'https://au.whales.org/wp-content/uploads/sites/3/2018/07/brydes-whale-jirayu-tour-ekkul-sg.jpg');
SELECT upsert_marine_species('Yellow-bellied sea snake', 'Hydrophis platurus', 'Creatures', 2, 60.0, 110.0, ARRAY['Open-ocean slicks', 'Drift lines near Bali'], 'Small fish at the surface', 'Truly pelagic; aggregates in calm slicks driven by currents.', 'High', true, 'Black top, bright yellow belly; occasionally drifts into Bali waters.', '5–10 years (est.)', 'Live-bearing (viviparous) at sea.', 'Current-driven drift; vagrant to Bali.', 'IUCN: Least Concern', 'Can absorb oxygen through skin—helpful at the surface.', 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Hydrophis_platurus_32924548.jpg');
SELECT upsert_marine_species('Saltwater crocodile', 'Crocodylus porosus', 'Creatures', 1, 270.0, 600.0, ARRAY['Estuaries', 'Coastal seas (rare vagrant)'], 'Fish, birds, mammals', 'Solitary ambush predator; capable of long sea voyages.', 'High', false, 'Very rare vagrant around Bali; extreme caution on remote coasts.', '50–70+ years', 'Egg-laying in nests; strong parental guarding.', 'Dispersal across seas; individuals can travel hundreds of km.', 'IUCN: Least Concern (protected in many nations)', 'Largest living reptile; salt glands enable life at sea.', 'https://images.theconversation.com/files/554133/original/file-20231016-29-woipe3.jpg?ixlib=rb-4.1.0&rect=60%2C1116%2C6720%2C3360&q=45&auto=format&w=1356&h=668&fit=crop');
SELECT upsert_marine_species('Wunderpus', 'Wunderpus photogenicus', 'Creatures', 3, 20.0, 40.0, ARRAY['Muck/sand', 'Twilight and night dives'], 'Small crustaceans and fish', 'Striking orange-brown and white pattern; crepuscular hunter.', 'Low', false, 'Delicate, long-armed octopus popular with macro photographers.', '~1 year', 'Semelparous; planktonic paralarvae.', 'None; site-faithful on muck patches.', 'IUCN: Data Deficient', 'Individuals can be ID’d by unique head-spot patterns.', 'https://www.montereybayaquarium.org/globalassets/mba/images/animals/octopus-and-kin/wonderpus-rw14-050.jpg?format=webp&quality=60');
SELECT upsert_marine_species('Spanish dancer nudibranch', 'Hexabranchus sanguineus', 'Creatures', 3, 20.0, 60.0, ARRAY['Reefs', 'Walls', 'Night dives'], 'Sponges', 'Graceful undulating swimming when disturbed.', 'Low', false, 'Large red dorid nudibranch; bright egg ribbons on reefs.', 'Months to ~1 year', 'Hermaphroditic; spiral egg ribbons on substrate.', 'None', 'IUCN: Not Evaluated', 'Hosts commensal shrimp that match its red coloration.', 'https://www.australiangeographic.com.au/wp-content/uploads/2021/02/spanish-dancer-nudibranch-1.jpg');
SELECT upsert_marine_species('“Pikachu” nudibranch', 'Thecacera pacifica', 'Creatures', 4, 2.0, 5.0, ARRAY['Rubble', 'Macro reefs'], 'Bryozoans and small sessile invertebrates', 'Conspicuous yellow body with dark-tipped rhinophores and cerata-like appendages.', 'Low', false, 'Tiny crowd favorite at Bali macro sites.', 'Months', 'Hermaphroditic; gelatinous ribbon eggs.', 'None', 'IUCN: Not Evaluated', 'Nicknamed after the anime character for its color scheme.', 'https://images.redseacreatures.com/creatures/images/pikachu-nudibranch/1715009275192-350614598.jpeg');
SELECT upsert_marine_species('Harlequin shrimp', 'Hymenocera picta', 'Creatures', 2, 3.0, 5.0, ARRAY['Reefs', 'Under coral heads'], 'Sea stars (specialist predator)', 'Pairs cooperate to flip and immobilize sea stars.', 'Low', false, 'Ornate cream-and-purple pattern; iconic macro subject.', '~2–3 years (est.)', 'Pairs; female carries egg masses under abdomen.', 'None', 'IUCN: Not Evaluated', 'Will feed a starfish arm to keep prey alive and fresh.', 'https://fantaseaaquariums.com/wp-content/uploads/2020/11/Harlequin-shrimp.jpg');
SELECT upsert_marine_species('Banded coral (boxer) shrimp', 'Stenopus hispidus', 'Corals', 4, 4.0, 6.0, ARRAY['Reef ledges', 'Crevices'], 'Scavenger; cleans parasites from fishes', 'Forms cleaning stations; long white antennae advertise service.', 'Low', false, 'Red-and-white banded arms with large chelae.', '~2–3 years', 'Pairs; female carries eggs, larvae planktonic.', 'None', 'IUCN: Not Evaluated', 'Often seen in pairs guarding a crevice like tiny boxers.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Boxer_shrimp_at_Batu_Moncho.JPG/1920px-Boxer_shrimp_at_Batu_Moncho.JPG');
SELECT upsert_marine_species('Skunk cleaner shrimp', 'Lysmata amboinensis', 'Creatures', 5, 4.0, 6.0, ARRAY['Reef cleaning stations'], 'Ectoparasites and dead tissue from client fishes', 'Sets up conspicuous cleaning posts; fearless with large fish.', 'Low', false, 'Cream stripe down a red body with long white antennae.', '3–5 years', 'Protandric simultaneous hermaphrodite; regularly broods eggs.', 'None', 'IUCN: Not Evaluated', 'Will even clean divers’ cuticles if you offer a hand!', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Lysmata_amboinensis_in_Tropicarium-Oceanarium_Budapest.JPG/2560px-Lysmata_amboinensis_in_Tropicarium-Oceanarium_Budapest.JPG');
SELECT upsert_marine_species('Orangutan crab', 'Achaeus japonicus', 'Creatures', 3, 1.0, 3.0, ARRAY['Anemones (often Bubble-tip)', 'Soft corals'], 'Suspended particles, detritus', 'Camouflages with long reddish setae (“hair”).', 'Low', false, 'Tiny, fuzzy decorator living among anemone tentacles.', '~1–2 years (est.)', 'Female carries eggs under abdomen.', 'None', 'IUCN: Not Evaluated', 'Often associates with the very anemone that hides it from predators.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Orang_Utan_Crab-Achaeus_japonicus_%2833048430982%29.jpg/1920px-Orang_Utan_Crab-Achaeus_japonicus_%2833048430982%29.jpg');
SELECT upsert_marine_species('Decorator crab', 'Camposcia retusa', 'Creatures', 3, 5.0, 7.0, ARRAY['Reefs', 'Rubble'], 'Omnivore; often nocturnal scavenger', 'Attaches sponges and algae as living camouflage.', 'Low', false, 'Lumpy body masked by encrusting “decorations.”', '~1–2 years (est.)', 'Egg-laying; planktonic larvae.', 'None', 'IUCN: Not Evaluated', 'Will redecorate itself if you gently remove its costume.', 'https://aquariumbreeder.com/wp-content/uploads/2024/03/Decorator-Crab-Camposcia-retusa-–-Detailed-Guide-Care-Diet-and-Breeding-2.jpg');
SELECT upsert_marine_species('Cushion star', 'Culcita novaeguineae', 'Creatures', 4, 20.0, 30.0, ARRAY['Reefs', 'Seagrass edges'], 'Algae, detritus, sometimes coral polyps', 'Slow grazer; juveniles look like stubby 5-armed stars.', 'Low', false, 'Pillow-shaped sea star common on tropical Indo-Pacific reefs.', 'Years to decades (est.)', 'Broadcast spawner; planktonic larvae.', 'None', 'IUCN: Not Evaluated', 'Adults lose the classic star shape as the disc inflates.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/CulcitanovguineaeJI1.jpg/500px-CulcitanovguineaeJI1.jpg');
SELECT upsert_marine_species('Brittle stars (typical reef species)', 'Ophiuroidea (e.g., Ophiothrix spp.)', 'Creatures', 5, 10.0, 30.0, ARRAY['Reef crevices', 'Under coral heads'], 'Detritus and plankton', 'Nocturnal; arms snake out from hiding to feed.', 'Low', false, 'Slender-armed echinoderms carpeting reefs at night.', 'Several years', 'Broadcast spawning; some brood under the disc.', 'None', 'IUCN: Not Evaluated', 'Can jettison arms to escape, then regrow them.', 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Ophiura_ophiura.jpg');
SELECT upsert_marine_species('Collector (pincushion) urchin', 'Tripneustes gratilla', 'Creatures', 4, 10.0, 15.0, ARRAY['Seagrass beds', 'Reef flats'], 'Algae and detritus', 'Covers itself with debris—hence “collector.”', 'Low', false, 'Round urchin with short spines; common in shallow habitats.', '5–10 years (est.)', 'Broadcast spawner; planktonic larvae.', 'None', 'IUCN: Not Evaluated/varies by subpopulation', 'Self-shading with shells and leaves may reduce UV exposure.', 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Collector_urchin.jpg');
SELECT upsert_marine_species('Slate pencil urchin', 'Heterocentrotus mammillatus', 'Creatures', 3, 8.0, 25.0, ARRAY['Wave-exposed reefs', 'Crevices'], 'Algae and biofilm', 'Massive blunt spines resist surf; often red or maroon.', 'Medium', false, 'Thick “pencil” spines up to ~10 cm; painful mechanical wounds possible.', 'Years', 'Broadcast spawner.', 'None', 'IUCN: Not Evaluated', 'Spines were historically used as writing “pencils.”', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Heterocentrotus_mammillatus_in_situ_from_Hawaii.JPG/500px-Heterocentrotus_mammillatus_in_situ_from_Hawaii.JPG');
SELECT upsert_marine_species('Flower urchin', 'Toxopneustes pileolus', 'Creatures', 2, 15.0, 20.0, ARRAY['Reefs', 'Seagrass', 'Rubble'], 'Algae, bryozoans, detritus', 'Often concealed by “flower” pedicellariae that can sting.', 'High', true, 'Among the most venomous urchins; keep wide berth.', 'Years', 'Broadcast spawner.', 'None', 'IUCN: Not Evaluated', 'Stinging pedicellariae can detach and keep injecting venom.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Erizo_de_flor_%28Toxopneustes_pileolus%29%2C_Zanzíbar%2C_Tanzania%2C_2024-06-01%2C_DD_134.jpg/1920px-Erizo_de_flor_%28Toxopneustes_pileolus%29%2C_Zanzíbar%2C_Tanzania%2C_2024-06-01%2C_DD_134.jpg');
SELECT upsert_marine_species('Magnificent sea anemone', 'Heteractis magnifica', 'Creatures', 4, 20.0, 100.0, ARRAY['Reef pinnacles', 'High-light slopes'], 'Zooxanthellae photosynthesis; captures zooplankton', 'Hosts multiple clownfish species; can slowly move to better light.', 'Low', true, 'Large, colorful anemone forming showy mounds on current-swept peaks.', 'Decades (very long-lived)', 'Sexual spawning; can divide asexually.', 'Sessile but capable of creeping relocation.', 'IUCN: Not Evaluated', 'Some individuals can span a full meter across.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/195293757/original.jpg');
SELECT upsert_marine_species('Giant carpet anemone', 'Stichodactyla gigantea', 'Creatures', 3, 30.0, 50.0, ARRAY['Shallow sand flats', 'Seagrass lagoons'], 'Photosynthesis plus meaty prey items', 'Very sticky; often half-buried with expanded oral disc.', 'Low', true, 'Shaggy tentacles; hosts several anemonefish species.', 'Many years (long-lived in the wild)', 'Sexual spawning; occasional asexual fission.', 'Minimal; may slowly shift location.', 'IUCN: Not Evaluated', 'Can irritate skin—avoid touching even when tempting!', 'https://upload.wikimedia.org/wikipedia/commons/1/17/A_ocellaris_2_Sesoko_Point_140904_LOWRES.jpg');
SELECT upsert_marine_species('Upside-down jellyfish', 'Cassiopea spp.', 'Creatures', 2, 10.0, 30.0, ARRAY['Shallow lagoons', 'Seagrass beds', 'Mangrove shallows'], 'Symbiotic algae plus trapped plankton', 'Rests bell-down on sand, pulsing to circulate water and light.', 'Low', true, 'Brownish frilly oral arms; can cause mild stings (“sea rash”).', 'Months to ~1–2 years', 'Alternates polyp and medusa stages; budding and sexual reproduction.', 'None; may bloom seasonally in lagoons.', 'IUCN: Not Evaluated', 'Can create mucus “stinging water” that irritates swimmers.', 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Fkeysmacro.jpg');
SELECT upsert_marine_species('Sea fans (gorgonians)', 'e.g., Annella spp.', 'Corals', 4, 60.0, 150.0, ARRAY['Current-swept walls', 'Drop-offs (Penida', 'Nusa)'], 'Suspension-feeding on plankton', 'Orient fan perpendicular to current for optimal feeding.', 'Low', false, 'Large lace-like fans in reds/oranges dominate Bali walls.', 'Decades (est.)', 'Broadcast spawners; colonies grow by branching.', 'Sessile', 'IUCN: Not Evaluated (varies by species)', 'Pygmy seahorses hide by matching the texture and color.', '');
SELECT upsert_marine_species('Hard corals (stony corals)', 'Order Scleractinia (e.g., Euphyllia spp.)', 'Corals', 5, 5.0, 300.0, ARRAY['All Bali reef zones', 'Penida MPA'], 'Zooxanthellae plus zooplankton capture', 'Framework builders; nightly polyp extension to feed.', 'Low', false, 'Primary reef builders; diversity and cover vary by site and currents.', 'Decades to centuries', 'Mass spawning events; asexual budding grows colonies.', 'Sessile; larval dispersal with currents.', 'Mixed—many species VU/EN, others NT/LC', 'Bali participates in synchronized coral-spawning nights after full moons.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/66883064/large.jpeg');
SELECT upsert_marine_species('Elephant ear sponge', 'Ianthella basta', 'Creatures', 3, 50.0, 150.0, ARRAY['Reefs with strong flow', 'Walls'], 'Filters bacteria and organic particles', 'Large fan-shaped sheets in high-flow corridors.', 'Low', false, 'Huge yellow to purple fan sponge; microbial symbioses are abundant.', 'Years to decades', 'Both sexual and asexual budding/regeneration.', 'Sessile', 'IUCN: Not Evaluated', 'Can exceed 1 m across; natural products from this sponge are studied.', 'https://upload.wikimedia.org/wikipedia/commons/3/38/Ianthella_basta.jpg');
SELECT upsert_marine_species('Christmas tree worm', 'Spirobranchus giganteus', 'Creatures', 5, 2.0, 5.0, ARRAY['Living coral heads'], 'Suspended plankton', 'Retracts instantly; operculum “door” caps its tube.', 'Low', false, 'Colorful twin spirals embedded in corals all over Bali reefs.', 'Years (multi-year residents on the same coral)', 'Broadcast spawner; larvae settle on corals and bore a tube.', 'Sessile after settlement', 'IUCN: Not Evaluated', 'Populations mirror the health of their host coral colonies.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Spirobranchus_giganteus_%28Red_and_white_christmas_tree_worm%29.jpg/1920px-Spirobranchus_giganteus_%28Red_and_white_christmas_tree_worm%29.jpg');
SELECT upsert_marine_species('Bobbit worm (sand striker)', 'Eunice aphroditois', 'Creatures', 2, 100.0, 300.0, ARRAY['Sandy muck', 'Reef edges (night)'], 'Ambush predator on fishes and invertebrates', 'Buries body; lightning-fast jaws snatch prey.', 'Medium', false, 'Elusive, very long worm seen on night dives; impressive strikes.', '3–5+ years (est.)', 'External fertilization; planktonic larvae.', 'None', 'IUCN: Not Evaluated', 'Largest specimens approach 3 m—longer than most divers.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Eunice_aphroditois.jpg/1280px-Eunice_aphroditois.jpg');
SELECT upsert_marine_species('Bluebell tunicate', 'Clavelina moluccensis', 'Creatures', 4, 0.0, 20.0, ARRAY['Shaded reef overhangs', 'Jetty pylons', 'Walls'], 'Filter-feeding on plankton', 'Colonial “little bottles” forming blue clusters.', 'Low', false, 'Each zooid 0.5–2.5 cm; colonies can carpet patches of reef.', 'Months to a few years (colonial turnover)', 'Hermaphroditic; larvae settle and clone into colonies.', 'Sessile; spreads by larvae', 'IUCN: Not Evaluated', 'Despite the look, they’re chordates—our distant cousins.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Clavelina_moluccensis_60641896.jpg/1920px-Clavelina_moluccensis_60641896.jpg');
SELECT upsert_marine_species('Lace bryozoans', 'Bugula spp.', 'Creatures', 4, 3.0, 15.0, ARRAY['Reef rock', 'Piers', 'Artificial structures'], 'Suspension-feeding on microplankton', 'Bushy colonies with tiny zooids operating like a city.', 'Low', false, 'Often mistaken for seaweeds; fine branching ‘lace’ fans.', 'Seasonal to multi-year colonies', 'Brooded larvae released to settle nearby.', 'Sessile; fouling colonies spread via larvae/rafts', 'IUCN: Not Evaluated', 'Some Bugula produce bioactive compounds under study.', 'https://upload.wikimedia.org/wikipedia/commons/5/51/Lace_bryozoan.jpg');
SELECT upsert_marine_species('Tiger cowry', 'Cypraea tigris', 'Creatures', 3, 8.0, 15.0, ARRAY['Reefs', 'Rubble under ledges'], 'Algae and sponges (grazing)', 'Nocturnal; mantle fully covers and polishes the shell.', 'Low', false, 'Large, glossy spotted cowry; prized shell but common regionally.', 'Years', 'Female broods egg capsules under her foot.', 'None', 'IUCN: Not Evaluated', 'Hawaiian forms include giants over 13 cm.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Cypraea_tigris_%28Tiger_cowrie%29.jpg/1920px-Cypraea_tigris_%28Tiger_cowrie%29.jpg');
SELECT upsert_marine_species('Vase sponge', 'Haliclona sp.', 'Creatures', 4, 2.0, 8.0, ARRAY['Tidepools', 'Reef flats', 'Seagrass beds', 'Shallow rock'], 'Filters bacteria and plankton from seawater', 'Colonies of small tubular ''vases'' with a single osculum each; steady pumping flow.', 'Low', false, 'Small olive-green tubular sponges common in Bali shallows; pitted surface and single opening are typical.', 'Years (slow-growing)', 'Broadcast spawning plus asexual budding/regrowth from fragments', 'Sessile', 'Not Evaluated', 'A fist-sized sponge can filter liters of water every minute.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Starfish_on_sponge_at_Sandy_Cove_DSC09670.JPG/1920px-Starfish_on_sponge_at_Sandy_Cove_DSC09670.JPG');
SELECT upsert_marine_species('Feather-duster worm', 'Sabellastarte sp.', 'Creatures', 4, 10.0, 30.0, ARRAY['Sand', 'Seagrass beds', 'Lagoon shallows'], 'Suspension-feeding on plankton', 'Extends a circular fan of radioles; snaps back into tube at the slightest disturbance.', 'Low', false, 'Tube-dwelling polychaete with a brown/tan fan; common on Bali’s sandy seagrass flats.', 'Several years', 'Broadcast spawner; planktonic larvae settle and build tubes', 'Sessile once settled', 'Not Evaluated', 'That ''feather'' is hundreds of tiny tentacles sorting food by size.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Pacific_Feather_Duster_Sabellastarte_sp.jpg/1920px-Pacific_Feather_Duster_Sabellastarte_sp.jpg');
SELECT upsert_marine_species('Tuxedo urchin', 'Mespilia globulus', 'Creatures', 4, 5.0, 8.0, ARRAY['Seagrass beds', 'Reef rubble', 'Shallow lagoons'], 'Algae and biofilm', 'Often carries shells or leaves on its body for camouflage and shade.', 'Low', false, 'Small, banded urchin with orange/red short spines over dark wedges; common in Bali shallows.', '2–5 years (est.)', 'Broadcast spawner; larvae drift as plankton before settling', 'None (benthic wanderer only)', 'Not Evaluated', 'Nicknamed ''tuxedo'' for its neat wedge pattern.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Mespilia_globulus_Indonesia.jpg/2560px-Mespilia_globulus_Indonesia.jpg');
SELECT upsert_marine_species('Wedge sea hare', 'Dolabella auricularia', 'Creatures', 4, 10.0, 30.0, ARRAY['Seagrass beds', 'Sandy lagoons'], 'Grazes algae on sand and seagrass', 'Slow, nocturnal grazer; can release purple ink when stressed.', 'Low', false, 'Bulky sea hare with rough, warty skin and a hidden internal shell; very common on Bali flats.', '~1 year', 'Lays long spaghetti-like egg ribbons; adults are short-lived and may die after spawning', 'None', 'Not Evaluated', 'Sometimes eaten in parts of Asia, but toxins from their algal diet make them a risky meal—best admired alive.', 'https://upload.wikimedia.org/wikipedia/commons/d/d1/Sea_hare_DSC01663.jpg');
SELECT upsert_marine_species('Sandfish sea cucumber', 'Holothuria scabra', 'Creatures', 4, 20.0, 40.0, ARRAY['Seagrass beds', 'Sandy lagoons', 'Reef flats'], 'Detritus and microalgae ingested from sand', 'Slow deposit-feeder; often half-buried and leaves meandering feeding tracks.', 'Low', false, 'Thick, pale grey-brown cucumber with irregular dark blotches and coarse texture; common on Bali flats.', '5–10 years (est.)', 'Broadcast spawner with planktonic larvae; widely farmed for restocking/sea ranching.', 'None (benthic wanderer only).', 'IUCN: Endangered (overharvested for trepang in much of its range).', 'A single sandfish can rework kilos of sand daily, cleaning and oxygenating the seabed.', 'https://upload.wikimedia.org/wikipedia/commons/5/54/Holothuria_scabra_60282695.jpg');
SELECT upsert_marine_species('Common spider conch', 'Lambis lambis', 'Creatures', 3, 15.0, 30.0, ARRAY['Seagrass beds', 'Shallow reef flats', 'Lagoons'], 'Algae and biofilm grazed from sand and seagrass blades', 'Uses its clawed operculum to ‘hop’ across the bottom; active at high tide.', 'Low', false, 'Large Strombidae sea snail with pink-orange aperture and a flared outer lip that bears finger-like ‘spines’.', '5–10 years (est.)', 'Egg masses laid in gelatinous strings; planktonic larvae before settling.', 'None (local movements only).', 'Not Evaluated globally; locally vulnerable to over-collecting—protected in some MPAs.', 'Their eyes sit on long stalks and they can ‘jump’ surprisingly far using the operculum as a kickstand.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Lambis_lambis.jpg/2560px-Lambis_lambis.jpg');
SELECT upsert_marine_species('Snake sea cucumber', 'Synapta maculata', 'Creatures', 4, 100.0, 300.0, ARRAY['Seagrass beds', 'Reef flats', 'Sandy rubble', 'Tidepools'], 'Deposit-feeder; picks up detritus and microalgae with sticky feeding tentacles', 'Very long, rope-like body; slow crawler with tiny ''anchor'' hooks in the skin; harmless and very fragile—don’t handle.', 'Low', false, 'Banded, snake-like sea cucumber that coils on shallow flats and lagoon edges; often mistaken for a sea snake.', 'Several years (est.)', 'Broadcast spawner with planktonic larvae; no Cuvierian tubules.', 'None (local benthic wanderer)', 'Not Evaluated', 'Can reach 3 m and still squeeze through tiny gaps by softening its body.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Reef1118_-_Flickr_-_NOAA_Photo_Library.jpg/1024px-Reef1118_-_Flickr_-_NOAA_Photo_Library.jpg');
SELECT upsert_marine_species('White-eyed moray', 'Gymnothorax thyrsoideus', 'Fishes', 5, 45.0, 70.0, ARRAY['Coral reefs', 'Rubble', 'Jetty pylons', 'Shallow lagoons'], 'Small fishes, shrimps, crabs', 'Crevice dweller; often seen out in the open by day around cleaning stations.', 'Medium', false, 'Slender dark moray with pale eyes and fine peppery speckles; very common in Bali shallows.', '10–15 years (est.)', 'Broadcast spawner; leptocephalus larvae drift weeks–months before settling.', 'None; generally site-faithful to a home crevice.', 'IUCN: Least Concern', 'Will let cleaner shrimps crawl into its mouth to pick parasites.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Greyface_Moray_%28Gymnothorax_thyrsoideus%29_%286067795691%29.jpg/2560px-Greyface_Moray_%28Gymnothorax_thyrsoideus%29_%286067795691%29.jpg');
SELECT upsert_marine_species('Fimbriated moray', 'Gymnothorax fimbriatus', 'Fishes', 3, 60.0, 100.0, ARRAY['Reef crevices', 'Harbor rubble', 'Shallow ledges'], 'Small fishes and crustaceans', 'Secretive; usually with just the head protruding from a hole.', 'Medium', false, 'Yellow-green body with dark-rimmed spots and a distinct black margin at the gill opening.', '10–15 years (est.)', 'Broadcast spawner; planktonic leptocephalus stage.', 'None', 'IUCN: Least Concern', 'The name refers to the dark ‘fringe’ (fimbriation) edging its spots.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Gymnothorax_fimbriatus.JPG/1024px-Gymnothorax_fimbriatus.JPG');
SELECT upsert_marine_species('Snowflake moray', 'Echidna nebulosa', 'Fishes', 4, 50.0, 100.0, ARRAY['Shallow reefs', 'Tide channels', 'Rubble'], 'Crabs, shrimps, small fishes', 'Often active at dusk; tolerant of very shallow water.', 'Medium', false, 'Pale body with yellow-black ‘snowflake’ blotches; chunky head and jaws.', '10–20 years (est.)', 'External spawner; larvae drift before settling on reefs.', 'None', 'IUCN: Least Concern', 'More of a crustacean specialist than many morays.', 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Snowflake_moray_in_Kona.jpg');
SELECT upsert_marine_species('Zebra moray', 'Gymnomuraena zebra', 'Fishes', 2, 80.0, 150.0, ARRAY['Reef crevices', 'Boulder fields'], 'Hard-shelled crabs, shrimps, sea urchins', 'Shy daytime hider; uses crushing molar-like teeth rather than sharp fangs.', 'Medium', false, 'Thick body with bold black-and-white bands from head to tail.', '15–20+ years (est.)', 'Broadcast spawner; long-lived leptocephalus larvae drift with currents.', 'None', 'IUCN: Least Concern', 'Its blunt teeth are perfect nutcrackers for urchins and crabs.', 'https://cdn2.reefapp.net/large/gymnomuraena-zebra-7d72f7d06d544062b7c6d0e199ba16c8.jpg');

-- =====================================================
-- VERIFICATION QUERIES
-- =====================================================
SELECT COUNT(*) as total_species FROM marine;
SELECT category, COUNT(*) as count FROM marine GROUP BY category ORDER BY count DESC;
SELECT rarity, COUNT(*) as count FROM marine GROUP BY rarity ORDER BY rarity;
SELECT name, scientific_name, category FROM marine WHERE venomous = true ORDER BY category, name;

-- =====================================================
-- SCRIPT COMPLETION
-- =====================================================
-- ✅ Complete dataset with all 73 species from CSV
-- ✅ Function-based approach for easier management
-- ✅ All data validated against database constraints
-- ✅ Timestamps automatically updated for modified records
-- ✅ Ready for production use